# Generated by Django 5.0.2 on 2024-04-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_task_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.CharField(max_length=100, verbose_name='Исполнитель'),
        ),
    ]
