# Generated by Django 5.0.2 on 2024-04-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.CharField(choices=[(1, 'admin'), (2, 'test'), (3, 'admin2'), (4, 'admin1'), (5, 'admin3'), (6, 'admin4'), (7, 'admin5'), (8, 'admin7'), (9, 'admin8'), (10, 'admin9'), (11, 'admin10'), (12, 'admin11'), (13, 'admin13'), (14, 'admin14')], max_length=100, verbose_name='Исполнитель'),
        ),
    ]
