# Generated by Django 5.0.2 on 2024-04-08 11:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_task_executor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.CharField(choices=[('admin', 'admin'), ('test', 'test'), ('admin2', 'admin2'), ('admin1', 'admin1'), ('admin3', 'admin3'), ('admin4', 'admin4'), ('admin5', 'admin5'), ('admin7', 'admin7'), ('admin8', 'admin8'), ('admin9', 'admin9'), ('admin10', 'admin10'), ('admin11', 'admin11'), ('admin13', 'admin13'), ('admin14', 'admin14')], max_length=100, verbose_name='Исполнитель'),
        ),
        migrations.CreateModel(
            name='Сomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текс')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
